# For full config options, check the docs: docs.serverless.com

# See the following link for details and examples on using API Endpoints
# with Serverlesson AWS Lambda:
# https://www.serverless.com/framework/docs/providers/aws/events/apigateway/

service: auditlog-api
frameworkVersion: "=1.70.0"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  sentry:
    dsn: https://1504b932aac241b9829ac8f543e703b6:75170a5ff33d46588e863e59992372cf@sentry.io/300108

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: us-west-2
  profile: auditlogs-api-serverless
  environment: ${file(./env.yaml):${opt:stage, self:provider.stage}}
  apiKeys:
    - value: ${file(./env.yaml):${opt:stage, self:provider.stage}.api_key}

functions:
  test:
    name: test-${opt:stage, self:provider.stage}
    handler: src/handlers/logs.test
    events:
      - http:
          path: test/
          method: get
  create-logs:
    name: create-logs-${opt:stage, self:provider.stage}
    handler: src/handlers/logs.create
    events:
      - http:
          path: att/
          method: post
          private: true
      - http:
          path: tmobile/
          method: post
          private: true
      - http:
          path: verizon/
          method: post
          private: true
      - http:
          path: sprint/
          method: post
          private: true
